// <auto-generated />
using System;
using DocsGen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocsGen.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocsGen.Models.Guarantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("text");

                    b.Property<string>("AcademicRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guarantors");
                });

            modelBuilder.Entity("DocsGen.Models.HeadOfSMC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("text");

                    b.Property<string>("AcademicRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeadsOfSMC");
                });

            modelBuilder.Entity("DocsGen.Models.KnowledgeBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KnowledgeBranches");
                });

            modelBuilder.Entity("DocsGen.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuarantorId")
                        .HasColumnType("integer");

                    b.Property<int>("HeadOfSMCId")
                        .HasColumnType("integer");

                    b.Property<int>("KnowledgeBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GuarantorId")
                        .IsUnique();

                    b.HasIndex("HeadOfSMCId");

                    b.HasIndex("KnowledgeBranchId");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("DocsGen.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DocsGen.Models.Syllabus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomHours")
                        .HasColumnType("integer");

                    b.Property<byte?>("CourseProjects")
                        .HasColumnType("smallint");

                    b.Property<byte?>("CourseWork")
                        .HasColumnType("smallint");

                    b.Property<string>("Credits")
                        .HasColumnType("text");

                    b.Property<string>("FormOfControl")
                        .HasColumnType("text");

                    b.Property<int?>("LabHours")
                        .HasColumnType("integer");

                    b.Property<int?>("LectureHours")
                        .HasColumnType("integer");

                    b.Property<int?>("PracticalHours")
                        .HasColumnType("integer");

                    b.Property<byte?>("R")
                        .HasColumnType("smallint");

                    b.Property<byte?>("RGR")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Semester")
                        .HasColumnType("smallint");

                    b.Property<int?>("TotalHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Syllabuses");
                });

            modelBuilder.Entity("DocsGen.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("text");

                    b.Property<string>("AcademicRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DocsGen.Models.TeacherLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SyllabusId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<byte>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SyllabusId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Type", "Year", "TeacherId", "SubjectId", "SpecialityId")
                        .IsUnique();

                    b.ToTable("TeacherLoads");
                });

            modelBuilder.Entity("DocsGen.Models.Speciality", b =>
                {
                    b.HasOne("DocsGen.Models.Guarantor", "Guarantor")
                        .WithOne("Speciality")
                        .HasForeignKey("DocsGen.Models.Speciality", "GuarantorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsGen.Models.HeadOfSMC", "HeadOfSMC")
                        .WithMany("Specialties")
                        .HasForeignKey("HeadOfSMCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsGen.Models.KnowledgeBranch", "KnowledgeBranch")
                        .WithMany("Specialities")
                        .HasForeignKey("KnowledgeBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarantor");

                    b.Navigation("HeadOfSMC");

                    b.Navigation("KnowledgeBranch");
                });

            modelBuilder.Entity("DocsGen.Models.TeacherLoad", b =>
                {
                    b.HasOne("DocsGen.Models.Speciality", "Speciality")
                        .WithMany("TeacherLoads")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsGen.Models.Subject", "Subject")
                        .WithMany("TeacherLoads")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsGen.Models.Syllabus", "Syllabus")
                        .WithMany("TeacherLoads")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocsGen.Models.Teacher", "Teacher")
                        .WithMany("TeacherLoads")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("Subject");

                    b.Navigation("Syllabus");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DocsGen.Models.Guarantor", b =>
                {
                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DocsGen.Models.HeadOfSMC", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("DocsGen.Models.KnowledgeBranch", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("DocsGen.Models.Speciality", b =>
                {
                    b.Navigation("TeacherLoads");
                });

            modelBuilder.Entity("DocsGen.Models.Subject", b =>
                {
                    b.Navigation("TeacherLoads");
                });

            modelBuilder.Entity("DocsGen.Models.Syllabus", b =>
                {
                    b.Navigation("TeacherLoads");
                });

            modelBuilder.Entity("DocsGen.Models.Teacher", b =>
                {
                    b.Navigation("TeacherLoads");
                });
#pragma warning restore 612, 618
        }
    }
}
